apiVersion: v1
kind: Secret
metadata:
  name: unm-server-secrets
  namespace: unm-server
  labels:
    app: unm-server
type: Opaque
data:
  # Base64 encoded secrets
  # Use: echo -n "your-secret" | base64
  jwt-secret: dW5tLXNlcnZlci1qd3Qtc2VjcmV0LWtleS1mb3ItcHJvZHVjdGlvbg==  # unm-server-jwt-secret-key-for-production
  api-key: dW5tLXNlcnZlci1hcGkta2V5LTEyMzQ1  # unm-server-api-key-12345
  redis-password: dW5tLXJlZGlzLXBhc3N3b3JkLTEyMzQ1  # unm-redis-password-12345
  netease-cookie: ""  # 网易云音乐Cookie (需要手动设置)
  qq-cookie: ""       # QQ音乐Cookie (需要手动设置)
  migu-cookie: ""     # 咪咕音乐Cookie (需要手动设置)
  joox-cookie: ""     # JOOX音乐Cookie (需要手动设置)
  youtube-key: ""     # YouTube API Key (需要手动设置)

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: unm-server
  labels:
    app: grafana
type: Opaque
data:
  admin-user: YWRtaW4=      # admin
  admin-password: YWRtaW4=  # admin (请在生产环境中修改)
