apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: unm-server-ssd
  labels:
    app: unm-server
provisioner: kubernetes.io/aws-ebs  # 根据云提供商调整
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: unm-server
  labels:
    app: redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: unm-server-ssd
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unm-server-logs-pvc
  namespace: unm-server
  labels:
    app: unm-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: unm-server-ssd
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unm-server-cache-pvc
  namespace: unm-server
  labels:
    app: unm-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: unm-server-ssd
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: unm-server
  labels:
    app: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: unm-server-ssd
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: unm-server
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: unm-server-ssd
  resources:
    requests:
      storage: 5Gi

---
# 本地开发用的PV示例（生产环境请使用云存储）
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-local
  labels:
    app: redis
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1  # 替换为实际节点名

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unm-server-logs-pv-local
  labels:
    app: unm-server
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/unm-server/logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1  # 替换为实际节点名

---
# NFS存储示例（适用于多节点共享）
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unm-server-shared-pv
  labels:
    app: unm-server
    type: nfs
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: nfs-server.example.com  # 替换为实际NFS服务器
    path: /exports/unm-server
  mountOptions:
    - nfsvers=4.1
    - hard
    - intr
