# 生产环境配置
app:
  mode: "production"
  debug: false

# 服务器配置
server:
  port: 5678
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  enable_cors: true
  cors_origins: []  # 生产环境需要明确指定允许的域名

# 日志配置
logging:
  level: "info"
  format: "json"  # 生产环境使用JSON格式便于日志收集
  output: "stdout"
  enable_caller: false
  enable_stacktrace: false

# 音源配置
sources:
  # 生产环境仅启用稳定的音源
  enabled_sources: ["gdstudio", "unm_server"]
  test_sources: ["gdstudio"]
  
  timeout: "30s"
  retry_count: 3

  unm_server:
    timeout: "30s"
    retry_count: 3
  
  gdstudio:
    timeout: "30s"
    retry_count: 3

  music_info_resolver:
    cache_ttl: "3600s"  # 生产环境缓存时间较长

# 缓存配置
cache:
  enabled: true
  ttl: "1h"
  max_size: "100MB"
  cleanup_interval: "10m"

# 性能配置
performance:
  max_concurrent_requests: 1000
  request_timeout: "30s"
  
  rate_limit:
    enabled: true  # 生产环境启用限流
    requests_per_minute: 100
    burst: 10
  
  connection_pool:
    max_idle_conns: 100
    max_idle_conns_per_host: 10
    idle_conn_timeout: "90s"

# 安全配置
security:
  enable_auth: true  # 生产环境启用认证
  # jwt_secret 和 api_key 从环境变量获取
  
  cors:
    enabled: true
    allowed_origins: []  # 需要在部署时配置
    allowed_methods: ["GET", "POST", "OPTIONS"]
    allowed_headers: ["Content-Type", "Authorization"]
    allow_credentials: false
    max_age: "12h"

# 监控配置
monitoring:
  enabled: true
  
  metrics:
    enabled: true
    port: 9090
  
  health_check:
    enabled: true
    interval: "30s"
  
  profiling:
    enabled: false  # 生产环境禁用性能分析

# 插件配置
plugins:
  middleware:
    - name: "cors"
      enabled: true
    - name: "logging"
      enabled: true
    - name: "recovery"
      enabled: true
    - name: "rate_limit"
      enabled: true
    - name: "auth"
      enabled: true

# 路由配置
routes:
  endpoints:
    # 生产环境移除调试端点
    search:
      middleware: ["cors", "logging", "rate_limit", "auth"]
    
    match:
      middleware: ["cors", "logging", "rate_limit", "auth"]
    
    ncmget:
      middleware: ["cors", "logging", "rate_limit", "auth"]
    
    other:
      middleware: ["cors", "logging", "rate_limit", "auth"]
    
    picture:
      middleware: ["cors", "logging", "cache"]
    
    lyric:
      middleware: ["cors", "logging", "cache"]
