# 基础配置文件 - 所有环境共享的配置
app:
  name: "music-api-proxy"
  version: "v2.0.0"
  description: "高性能音乐API代理服务"

# 服务器配置
server:
  host: "0.0.0.0"
  port: 5678
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  max_header_bytes: 1048576  # 1MB
  enable_cors: true
  cors_origins: ["*"]
  cors_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  cors_headers: ["*"]

# 日志配置
logging:
  level: "info"
  format: "json"
  output: "stdout"
  enable_caller: true
  enable_stacktrace: false

# 音源配置
sources:
  # 默认音源列表
  default_sources: ["gdstudio", "unm_server"]
  enabled_sources: ["gdstudio", "unm_server"]
  test_sources: ["gdstudio"]
  timeout: "30s"
  retry_count: 3

  # UNM Server配置
  unm_server:
    enabled: true
    base_url: "https://api-unm.imixc.top"
    api_key: ""
    timeout: "30s"
    retry_count: 3
    user_agent: "Music-API-Proxy-HTTPClient/v2.0.0 (Linux; X86_64; go1.21)"

  # GDStudio API配置
  gdstudio:
    enabled: true
    base_url: "https://music-api.gdstudio.xyz/api.php"
    api_key: ""
    timeout: "30s"
    retry_count: 3
    user_agent: "Music-API-Proxy-HTTPClient/v2.0.0 (Linux; X86_64; go1.21)"

  # 音乐信息解析器配置
  music_info_resolver:
    enabled: true
    timeout: "10s"
    cache_ttl: "3600s"  # 缓存时间1小时
    
    # 搜索回退配置
    search_fallback:
      enabled: true
      keywords: ["hello", "love", "music", "song", "popular"]
      max_results: 20
      max_keywords: 3

# 缓存配置
cache:
  enabled: true
  type: "memory"  # memory, redis
  ttl: "1h"
  max_size: "100MB"
  cleanup_interval: "10m"

# 性能配置
performance:
  max_concurrent_requests: 1000
  request_timeout: "30s"
  rate_limit:
    enabled: false
    requests_per_minute: 100
    burst: 10
  
  # 连接池配置
  connection_pool:
    max_idle_conns: 100
    max_idle_conns_per_host: 10
    idle_conn_timeout: "90s"

# 安全配置
security:
  enable_auth: false
  jwt_secret: ""  # 从环境变量获取
  api_key: ""     # 从环境变量获取
  
  # CORS配置
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    expose_headers: []
    allow_credentials: false
    max_age: "12h"

# 监控配置
monitoring:
  enabled: false
  metrics:
    enabled: false
    path: "/metrics"
    port: 9090
  
  health_check:
    enabled: true
    path: "/health"
    interval: "30s"
  
  profiling:
    enabled: false
    path: "/debug/pprof"

# 插件配置
plugins:
  enabled: []
  config_path: "./plugins"
  
  # 中间件插件
  middleware:
    - name: "cors"
      enabled: true
    - name: "logging"
      enabled: true
    - name: "recovery"
      enabled: true
  
  # 音源插件
  sources:
    - name: "gdstudio"
      enabled: true
    - name: "unm_server"
      enabled: true

# 路由配置
routes:
  api_prefix: "/api/v1"
  
  # API路由定义
  endpoints:
    search:
      path: "/search"
      methods: ["GET"]
      middleware: ["cors", "logging", "rate_limit"]
      sources: ["gdstudio", "unm_server"]
    
    match:
      path: "/match"
      methods: ["GET"]
      middleware: ["cors", "logging"]
      sources: ["gdstudio", "unm_server"]
    
    ncmget:
      path: "/ncmget"
      methods: ["GET"]
      middleware: ["cors", "logging"]
      sources: ["gdstudio", "unm_server"]
    
    other:
      path: "/other"
      methods: ["GET"]
      middleware: ["cors", "logging"]
      sources: ["gdstudio", "unm_server"]
    
    picture:
      path: "/picture"
      methods: ["GET"]
      middleware: ["cors", "logging", "cache"]
      sources: ["gdstudio"]
    
    lyric:
      path: "/lyric"
      methods: ["GET"]
      middleware: ["cors", "logging", "cache"]
      sources: ["gdstudio"]
